#include <iostream>
#include <iomanip>
using namespace std;

int main()
{
  const double rateA = 15.00;
  const double rateB = 12.00;
  const double rateC = 9.00;

  double amountRateA, amountRateB, amountRateC, totalticketsSold;
  double totalRateA, totalRateB, totalRateC, totalSales;

cout << "How many tickets for each class A,B and C were sold respectively?" << endl;
cin >> amountRateA >> amountRateB >> amountRateC;
totalRateA = amountRateA * rateA;
totalRateB = amountRateB * rateB;
totalRateC = amountRateC * rateC;
totalticketsSold = amountRateA + amountRateB + amountRateC;
totalSales = totalRateA + totalRateB + totalRateC;


cout << "The total amount of income generated by each seating class is $" << fixed << setprecision(2) << totalSales;

return 0;
}

